version: "3.8"
services:
  app:
    build:
      context: ./
    image: apif
    container_name: API
    ports:
      - "3001:3111"
    volumes:
      - type: bind
        source: ./
        target: /home/node/app
        read_only: true
    command: node ace serve --watch
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ../sql-data/db:/var/lib/mysql
    ports:
      - "3312:3306"
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "farmageo"
      MYSQL_ROOT_PASSWORD: "dockerpass"
      MYSQL_USER: "dan"
      MYSQL_PASSWORD: "secret"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - 80
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
