version: "3.2"
services:
  app:
    restart: always
    build:
      context: ./
    image: apif
    container_name: API
    ports:
      - "3111:3111"
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: node ace serve --watch
volumes:
  node_modules: {}
